name = input("What is your name? ")
print(f"Good day, {name}. Welcome to the terminal.")
print("I am learning Python and Git.")
department = input("What is your department? ")
print(f"Good morning, {name}. Welcome to the terminal.")
print("THIS IS AN EXPERIMENTAL VERSION OF MY TICKET TRACKER!")
